import Link from "next/link"
import { ArrowLeft, Calendar, MapPin, Users } from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"
import { archiveDestellos } from "@/lib/site-config"

export const metadata = { title: "Destellos del Desierto | Archivo TEDxTecnológico de Monterrey", description: "Archivo histórico de la edición Destellos del Desierto." }

export default function DestellosArchivePage() {
  const edition = archiveDestellos
  return <main className="min-h-screen bg-background"><section className="relative overflow-hidden py-28"><div className="absolute inset-0 bg-cover bg-center opacity-35" style={{ backgroundImage: `url(${edition.hero_image})` }} /><div className="absolute inset-0 bg-background/80" /><div className="container relative mx-auto max-w-5xl px-4"><Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" />Volver a la edición activa</Link><p className="mb-4 text-sm font-semibold uppercase tracking-[0.25em] text-primary">Archivo histórico</p><h1 className="max-w-3xl text-5xl font-black tracking-tight md:text-7xl">{edition.edition_tagline}</h1><p className="mt-6 max-w-2xl text-xl leading-relaxed text-muted-foreground">{edition.intro_text}</p></div></section><section className="container mx-auto max-w-5xl px-4 pb-20"><div className="grid gap-6 md:grid-cols-3"><Card><CardContent className="flex items-center gap-4 p-6"><Calendar className="size-8 text-primary" /><div><p className="text-sm text-muted-foreground">Fecha</p><p className="font-semibold">27 de febrero de 2026</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-4 p-6"><MapPin className="size-8 text-primary" /><div><p className="text-sm text-muted-foreground">Lugar</p><p className="font-semibold">{edition.venue_detail}</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-4 p-6"><Users className="size-8 text-primary" /><div><p className="text-sm text-muted-foreground">Edición</p><p className="font-semibold">TEDxTecnológico de Monterrey</p></div></CardContent></Card></div><div className="mt-12 rounded-2xl border bg-card p-8"><h2 className="text-3xl font-bold">Sobre esta edición</h2><p className="mt-4 max-w-3xl leading-relaxed text-muted-foreground">Esta página conserva la memoria pública de Destellos del Desierto. La nueva edición se administra por separado desde Configuración.</p></div></section></main>
}
